name: "Motion Detection Add-On"
description: "Add motion detection sensors to RTSP feeds"
version: "0.1.0"
slug: "motion_detection_addon"
init: false
arch:
  - amd64
  - aarch64

options:
  webui: "http://[HOST]:[PORT:32834]/"
  host_network: true