name: "Motion Detection Add-On"
description: "Add motion detection sensors to RTSP feeds"
version: "0.7.6"
slug: "motion_detection_addon"
init: false
arch:
- amd64
- aarch64
url: https://github.com/bcpearce/hass-motion-detection-addon
webui: "http://[HOST]:[PORT:32834]/"
host_network: true
homeassistant_api: true
icon: mdi:motion-sensor
options:
  feeds: []
  url: ""
  entity_id: "binary_sensor.motion_detected"

schema:
  feeds:
  - name: str
    sourceUrl: url
    hassEntityId: str
    hassFriendlyName: str?
    sourceUsername: str?
    sourcePassword: password?   #pragma: allowlist secret
    sourceToken: password?
    detectionDebounce: int(,3600)?
    detectionSize: str?

environment:
  HASS_URL: http://supervisor
