stages:
  - container-setup
  - lint
  - setup
  - build
  - test
  - release

variables:
  CONTAINER_BUILD_IMAGE: $CI_REGISTRY_IMAGE/build:$CI_COMMIT_REF_SLUG
  CONTAINER_RUN_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_TAG_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  VCPKG_DEFAULT_BINARY_CACHE: $CI_PROJECT_DIR/.cache/vcpkg-binary-cache
  PRE_COMMIT_HOME: $CI_PROJECT_DIR/.cache/pre-commit
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

.docker:
  image: docker:28.1
  tags: [dind]
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - echo "$DOCKER_HUB_TOKEN" | docker login --username $DOCKER_HUB_USER --password-stdin

.cmake:
  image: $CONTAINER_BUILD_IMAGE
  tags: [cpp, vcpkg]
  before_script:
    - mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
  cache:
    - key: cache-vcpkg
      paths:
        - .cache/vcpkg-binary-cache

docker:setup:
  stage: container-setup
  extends: .docker
  script:
    - docker build --tag $CONTAINER_BUILD_IMAGE docker/ci
    - docker push $CONTAINER_BUILD_IMAGE

lint:
  image: python:3.13
  stage: lint
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files
  cache:
    - key:
        files:
        - .pre-commit-config.yaml
      paths:
        - .cache/pre-commit
        - .cache/pip

include:
  - local: build.gitlab-ci.yml
    inputs:
      PRESET: Release
  - local: build.gitlab-ci.yml
    inputs:
      PRESET: Debug

docker:register:
  stage: release
  extends: .docker
  needs:
    - cmake:pack-deb:Release
  script:
    - cp build/Release/*.deb ./docker/deploy
    - cd ./docker/deploy
    - DEB_FILE=$(find -type f -name motiondetection*.deb)
    - echo "Found $DEB_FILE to install in container"
    - docker build --tag $CONTAINER_RUN_IMAGE --build-arg MOTION_DETECTION_DEB=$DEB_FILE .
    - docker tag $CONTAINER_RUN_IMAGE $DOCKER_HUB_USER/hass-motion-detection-addon:dev
    - docker push $CONTAINER_RUN_IMAGE
    - docker push $DOCKER_HUB_USER/hass-motion-detection-addon:dev

docker:register:release:
  stage: release
  extends: .docker
  needs:
    - docker:register
  script:
    - docker pull $CONTAINER_RUN_IMAGE
    - docker tag $CONTAINER_RUN_IMAGE $CONTAINER_RELEASE_IMAGE $CONTAINER_TAG_IMAGE
    - docker tag $CONTAINER_RUN_IMAGE $DOCKER_HUB_USER/hass-motion-detection-addon:latest $DOCKER_HUB_USER/hass-motion-detection-addon:$CI_COMMIT_TAG
    - docker push $CONTAINER_RELEASE_IMAGE

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG