spec:
  inputs:
    PRESET:
      options: [Debug, Release]
---

cmake:build:$[[ inputs.PRESET ]]:
  stage: build
  extends: .cmake
  variables:
    PRESET: $[[ inputs.PRESET ]]
  script:
    - mkdir -p build/$PRESET && cd build/$PRESET
    - cmake ../.. --preset=$PRESET
    - cmake --build .
  artifacts:
    paths:
      - build/$PRESET/MotionDetection
      - build/$PRESET/*.so
      - build/$PRESET/tests/*Tests
      - build/$PRESET/**/*.cmake
      - build/$PRESET/**/*.txt
    when: on_success
    expire_in: "1 day"

cmake:test:$[[ inputs.PRESET ]]:
  stage: test
  extends: .cmake
  variables:
    CTEST_OUTPUT_ON_FAILURE: 1
    PRESET: $[[ inputs.PRESET ]]
  script:
    - cd build/$PRESET
    - ctest --output-junit TestResults.xml
  artifacts:
    when: always
    paths:
    - build/$PRESET/TestResults.xml
    reports:
      junit: build/$PRESET/TestResults.xml

cmake:pack-deb:Release:
  stage: release
  extends: .cmake
  needs:
    - cmake:build:Release
  variables:
    PRESET: Release
  script:
    - cd build/$PRESET
    - DEB_FILE=$(echo "motiondetection_${CI_COMMIT_REF_NAME}_$(dpkg --print-architecture).deb")
    - cpack -G DEB -DCPACK_PACKAGE_FILE_NAME=$DEB_FILE
  artifacts:
    paths:
    - build/$PRESET/*.deb