name: End to End Test
description: Runs end to end testing using Python
inputs:
  motion-detection-exec:
    description: MotionDetection executable
    required: true
  rtsp-server-exec:
    description: RTSP Server executable
    required: true
  resource-file:
    description: H264 Test resource file
    required: true
    default: "tests/res/test.264"
  juint-xml:
    description: JUNIT XML output
    required: true
    default: "test_detail_end_to_end.xml"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv and cache dependencies
      uses: astral-sh/setup-uv@v1
      with:
        enable-cache: true

    - name: Install project dependencies
      shell: bash
      run: uv sync

    - name: Run tests (example command)
      shell: bash
      run: |
        uv run pytest \
        --junit-xml=${{ inputs.junit-xml }} \
        -s tests/end_to_end/ \
        --rtsp_server=${{ inputs.rtsp-server-exec }} \
        --motion_detection=${{ inputs.motion-detection-exec }} \
        --resource_file=${{ inputs.resource-file }}