name: Release

on:
  workflow_run:
    workflows: ["Build Project (Linux)"]
    types:
    - completed

jobs:
  release-debian:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          path: dpkg
          pattern: motion-detection-deb-*
          run-id: ${{ github.event.workflow_run.id }}
          merge-multiple: true
          github-token: ${{ secrets.GH_ACTIONS_TOKEN }}
      - name: Draft Release
        uses: softprops/action-gh-release@v2
        with:
          files: dpkg/*